### ISSUE TITLE
为什么是json的值是retcode100001

### ISSUE THREAD

**Issue by x5word** [nws0507/tanbaishuo#3]
Traceback (most recent call last):
  File "C:\Users\whoami\Desktop\tanbaishuo.py", line 163, in <module>
    getuid(s)
  File "C:\Users\whoami\Desktop\tanbaishuo.py", line 107, in getuid
    miwen=json['result']['ss_uin']
KeyError: 'result'

**Comment by jwjjgs** [comment]
腾讯已经修复漏洞了

**Comment by ananas-xxj** [comment]
一样的，上面的昵称看不到。fromNick': 'һ����ʶ6�������', 'fromEncodeUin': '*S1*oKvPoK6kow65oi4PoK6ioKEP'

**Comment by abc100m** [comment]
---删了也，没有人答的
